// Generated by https://quicktype.io

export interface PokemonByNameResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  PokemonByNameList[];
}

export interface PokemonByNameList {
    name: string;
    url:  string;
}
